# Generated by Django 5.2.8 on 2025-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
