# Generated by Django 6.0 on 2026-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_product_name_ru_alter_product_name_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Cancelled", "Cancelled"),
                ],
                db_index=True,
                default="Received",
                max_length=20,
            ),
        ),
    ]
